# try:
#     a=int(input('введите число'))
# except:
#     print('возникла ошибка')
# else:
#     print('ошибки нет')
# finally:
#     print('программа закончила свою работу')

# assert 1>0
# assert 1<0

# b=''
# try:
#     assert isinstance(b,int)
# except:
#     b=int(1)

# class MyEx(Exception):
#     def __init__(self,message) -> None:
#         super().__init__()
#         self.message=message
#     def __str__(self) -> str:
#         return self.message
# raise MyEx('MyExIsRaised')

